language: emacs-lisp
env:
  - EMACS=emacs
before_install:
  - curl -fsSkL https://raw.github.com/rejeep/cask.el/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
install:
  # Install our packages
  - make EMACS=$EMACS deps
script:
  # Byte-compile the file
  - make EMACS=$EMACS EMACSFLAGS="${EMACSFLAGS}" compile
